services:
  register:
    image: register
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
  # "db" service
  db:
    # Name of the image to be pulled from Docker Hub.
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: p
      MYSQL_DATABASE: register # Automatically create the 'HC' database
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql # Correct volume for MySQL
      - ./dbdump.sql:/docker-entrypoint-initdb.d/db.sql # Load db.sql on initialization
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
